seed: 42
do_train: True
do_predict: True 
do_ED_infer: False 

task_name: EE
paradigm: sequence_labeling

output_dir: output/Event-Extraction
type2id_path: ../data/type2id.json 
train_file: ../data/train.json
validation_file: ../data/dev.json
test_file: ../data/test_without_labels.json
language: Chinese
test_exists_labels: False 

truncate_in_batch: True
return_token_type_ids: True 
truncate_seq2seq_output: False

model_type: bert
model_name_or_path: bert-base-chinese
hidden_size: 768
aggregation: none 

num_train_epochs: 10
max_seq_length: 180
max_out_length: 128
dataloader_num_workers: 2

generation_max_length: 128
generation_num_beams: 4
predict_with_generate: True 
ignore_pad_token_for_loss: True 

per_device_train_batch_size: 32
per_device_eval_batch_size: 64
gradient_accumulation_steps: 2
# eval_accumulation_steps: 4
learning_rate: 3.0e-5
weight_decay: 1.0e-5
warmup_ratio: 0.1 
max_grad_norm: 1
optim: adamw_torch

load_best_model_at_end: True
metric_for_best_model: micro_f1 
greater_is_better: True 

logging_strategy: epoch
# logging_steps: 100
evaluation_strategy: epoch
# eval_steps: 500
save_strategy: epoch
# save_steps: 500

overwrite_output_dir: True
save_total_limit: 2

